### ISSUE TITLE
Cannot run twice

### ISSUE THREAD

**Issue by TigerWolf** [ohr486/ansible-elixir#8]
Hi, I just started using this playbook. When running the playbook a second time I get this error:

`TASK: [ohr486.elixir | build erlang] ******************************************
failed: [45.55.74.119] => {"changed": true, "cmd": ["/usr/local/bin/kerl", "build", "18.1", "18.1"], "delta": "0:00:00.013953", "end": "2015-10-07 05:22:35.433923", "rc": 1, "start": "2015-10-07 05:22:35.419970", "warnings": []}
stdout: There's already a build named 18.1`

Is this meant to be happening? Am I doing something wrong?

EDIT: It looks like kerl deletes the build directory `erlang_build_dir: /tmp/kerl/builds` after install.

**Comment by ohr486** [comment]
I'm sorry answer is delayed.

> It looks like kerl deletes the build directory erlang_build_dir: /tmp/kerl/builds after install.

If `kerl cleanup` is executed, erlang_build_dir will be deleted.
But `{HOME}/.kerl/otp_builds` and `{HOME}/.kerl/otp_installations` will be remains.

Once this happens if, playbook will dump these error messages.

**Comment by ohr486** [comment]
I'll fix this problem soon.

**Comment by lsigauke** [comment]
I have the same issue as above, I installed the role today  and ran it once, when I tried to run it again I was faced with the error below, is there another way around this?

I'm using the sole like this

    - { role: ohr486.elixir, erlang_version: 19.0, elixir_version: v1.4.1, erl_configure_options: '--enable-hipe --enable-smp-support', become: yes }


```
TASK [ohr486.elixir : build erlang] ********************************************************************************************************
fatal: [test_serv]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/kerl", "build", "19.0", "19.0"], "delta": "0:00:00.016811", "end": "2017-05-18 14:51:55.043183", "failed": true, "rc": 1, "start": "2017-05-18 14:51:55.026372", "stderr": "", "stderr_lines": [], "stdout": "There's already a build named 19.0", "stdout_lines": ["There's already a build named 19.0"]}
```
